name: Build

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  ubuntu-24-gcc:
    name: Ubuntu 24.04 - GCC
    runs-on: gcc:10.1.0

    steps:
      - uses: actions/checkout@v4

      - name: Versión del compilador
        run: gcc --version

      - name: Build
        run: make rebuild CC=gcc